export const PRODUCTS_RECEIVED = "PRODUCTS_RECEIVED";
export const ADD_TO_CART = "ADD_TO_CART";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export const CHANGE_ROUTE = "CHANGE_ROUTE";

export const UPDATE_XR = "UPDATE_XR";
export const XR_FETCH_ERROR = "XR_FETCH_ERROR";
export const XR_FETCH_SECCESS = "XR_FETCH_SECCESS";
